version: "3"

services:
  app:
    build: ./app
    env_file: ./app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: /app/utils/wait-for-it.sh db:5432 -- bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
