# Generated by Django 2.1.2 on 2018-11-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181106_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.Story'),
        ),
    ]
