# Generated by Django 2.1.2 on 2018-11-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181106_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.Article'),
            preserve_default=False,
        ),
    ]
