# Generated by Django 2.1.2 on 2018-11-10 08:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('core', '0005_auto_20181106_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
