# Generated by Django 2.1.2 on 2018-11-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181110_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='story',
            name='keywords',
        ),
    ]
