# Generated by Django 2.1.2 on 2018-11-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_article_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.URLField(max_length=255),
        ),
    ]
